spring: 
 application: 
  name: FDB2Mysql
  
  # Configurações do banco de dados Firebird
firebird: 
 datasource: 
 url: jdbc:firebirdsql://localhost:3050/firebird_db
 username: firebird_user
 password: firebird_password
 driver-class-name: org.firebirdsql.jdbc.FBDriver

# Configurações do banco de dados MySQL
mysql:
 datasource: 
  url: jdbc:mysql://localhost:3306/mysql_db
  username: mysql_user
  password: mysql_password
  driver-class-name: com.mysql.cj.jdbc.Driver

